### ISSUE TITLE
momory leak

### ISSUE THREAD

**Issue by ghost** [cmatomic/makemkv-AppImage#1]
I was using in a debian 10 cinammon, and it appears having a memory leak, I ran a machine with a 4 gb of ram and also a core i7, when it's converting some video it took all whole ram memory and freeze the system after that I need to shutdown the pc.

**Comment by cmatomic** [comment]
Makemkv does not convert any type of video, simply transfers the contents of a DVD or blu-ray to MKV format.
I'm not the makemkv developer, try installing as they say in the official forum of the program.
https://www.makemkv.com/forum/viewtopic.php?f=3&t=224

**Comment by cmatomic** [comment]
I tested no on Debian 10 live "cd" and nothing you say happened.
Everything went normal to debian but there are some bugs in the graphical interface
![Screenshot from 2019-10-07 08-09-14](https://user-images.githubusercontent.com/33186553/66302201-01b1d880-e8e8-11e9-98b4-65e7d137028d.png)

**Comment by ghost** [comment]
thanks for the answer. I try it!

Em seg, 7 de out de 2019 às 06:51, cmatomic <notifications@github.com>
escreveu:

**Comment by ghost** [comment]
hi howdy?
how do you pack vlc as appimage?

i am using your recipe for do vlc as appimage in version 3.0.9 ? it's
working the appdir, but i got some issues for example when I try to pack
appears this

More than one architectures were found of the AppDir source directory
"squashfs-root"
A valid architecture with the ARCH environmental variable should be provided
e.g. ARCH=x86_64 appimagetool ...

second is the

Fontconfig error: Cannot load default config file

I'ma doing under debian 10, how do I solve this?

Em seg, 7 de out de 2019 às 19:42, Lucas Machado zainote <
lucasmzainote@gmail.com> escreveu:

**Comment by cmatomic** [comment]
You can see here:
https://github.com/cmatomic/RecipesAppimage/tree/master/VLCplayerSnap
https://github.com/cmatomic/RecipesAppimage/tree/master/SnapAppimage
https://github.com/cmatomic/RecipesAppimage/tree/master/squashfs-tools

"More than one architectures were found of the AppDir source directory
"squashfs-root"
A valid architecture with the ARCH environmental variable should be provided
e.g. ARCH=x86_64 appimagetool ..."
here is an example:
https://github.com/cmatomic/Appimage-003/blob/master/build.sh
any other questions related to vlc do in the following related place
https://github.com/cmatomic/RecipesAppimage
